/**
 * Public Action Policy Registry (Phase S6.3).
 *
 * Machine-verifiable inventory mapping every public Server Action to its:
 * - Rate limit policy (S6.2 taxonomy)
 * - Key resolver
 * - Resource bounds
 * - Authorization model
 *
 * Required invariant:
 * - unmapped public actions = 0
 * - duplicate/conflicting policy mappings = 0
 */

import { readFileSync } from "node:fs";
import { RATE_LIMITS, type RateLimitPolicy } from "./rate-limit";

export type KeyResolverType =
  | "userAndOrg"
  | "userOrIp"
  | "ipOnly"
  | "invitationTokenPrefixBucket"
  | "custom";

export interface ActionPolicyMapping {
  readonly actionName: string;
  readonly modulePath: string;
  readonly policy: RateLimitPolicy;
  readonly keyResolver: KeyResolverType;
  readonly resourceBounds: string;
  readonly authorization: string;
}

export const PUBLIC_ACTION_MODULES = [
  "src/features/approvals/actions.ts",
  "src/features/auth/actions.ts",
  "src/features/auth/actions/demo-login.ts",
  "src/features/calendar/actions.ts",
  "src/features/clients/actions.ts",
  "src/features/deliverables/actions.ts",
  "src/features/files/actions.ts",
  "src/features/meetings/actions.ts",
  "src/features/meetings/queries.ts",
  "src/features/notifications/actions.ts",
  "src/features/notifications/queries.ts",
  "src/features/organizations/actions.ts",
  "src/features/organizations/departments/actions.ts",
  "src/features/organizations/onboarding-actions.ts",
  "src/features/projects/actions.ts",
  "src/features/revisions/actions.ts",
  "src/features/search/actions.ts",
  "src/features/shares/actions/index.ts",
  "src/features/tasks/actions.ts",
  "src/features/timelines/actions.ts",
  "src/features/users/actions.ts",
  "src/features/users/admin/actions.ts",
  "src/features/workforce/attendance/actions.ts",
  "src/features/workforce/attendance/form-actions.ts",
  "src/features/workforce/attendance/read-model-actions.ts",
  "src/features/workforce/corrections/actions.ts",
  "src/features/workforce/corrections/form-actions.ts",
  "src/features/workforce/employees/actions.ts",
  "src/features/workforce/shared/policy-actions.ts",
  "src/lib/agents/actions.ts",
  "src/lib/automation/actions.ts",
] as const;

export const ACTION_POLICY_REGISTRY: Record<string, ActionPolicyMapping> = {
  "src/features/approvals/actions.ts::createApprovalCycle": {
    actionName: "createApprovalCycle",
    modulePath: "src/features/approvals/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/approvals/actions.ts::submitReview": {
    actionName: "submitReview",
    modulePath: "src/features/approvals/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/approvals/actions.ts::delegateReview": {
    actionName: "delegateReview",
    modulePath: "src/features/approvals/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/approvals/actions.ts::resolveCondition": {
    actionName: "resolveCondition",
    modulePath: "src/features/approvals/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/approvals/actions.ts::getPendingApprovalsCount": {
    actionName: "getPendingApprovalsCount",
    modulePath: "src/features/approvals/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/auth/actions.ts::signInWithPassword": {
    actionName: "signInWithPassword",
    modulePath: "src/features/auth/actions.ts",
    policy: RATE_LIMITS.authMutation,
    keyResolver: "ipOnly",
    resourceBounds: "email max 255, password max 128",
    authorization: "public / unauthenticated",
  },
  "src/features/auth/actions.ts::signInWithMagicLink": {
    actionName: "signInWithMagicLink",
    modulePath: "src/features/auth/actions.ts",
    policy: RATE_LIMITS.authMutation,
    keyResolver: "ipOnly",
    resourceBounds: "email max 255, password max 128",
    authorization: "public / unauthenticated",
  },
  "src/features/auth/actions.ts::signInWithGoogle": {
    actionName: "signInWithGoogle",
    modulePath: "src/features/auth/actions.ts",
    policy: RATE_LIMITS.authMutation,
    keyResolver: "ipOnly",
    resourceBounds: "email max 255, password max 128",
    authorization: "public / unauthenticated",
  },
  "src/features/auth/actions.ts::signOut": {
    actionName: "signOut",
    modulePath: "src/features/auth/actions.ts",
    policy: RATE_LIMITS.authMutation,
    keyResolver: "ipOnly",
    resourceBounds: "email max 255, password max 128",
    authorization: "public / unauthenticated",
  },
  "src/features/auth/actions/demo-login.ts::enterDemoWorkspace": {
    actionName: "enterDemoWorkspace",
    modulePath: "src/features/auth/actions/demo-login.ts",
    policy: RATE_LIMITS.authMutation,
    keyResolver: "ipOnly",
    resourceBounds: "email max 255, password max 128",
    authorization: "public / unauthenticated",
  },
  "src/features/calendar/actions.ts::getCalendarMonthAction": {
    actionName: "getCalendarMonthAction",
    modulePath: "src/features/calendar/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/clients/actions.ts::getClients": {
    actionName: "getClients",
    modulePath: "src/features/clients/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/clients/actions.ts::getClientById": {
    actionName: "getClientById",
    modulePath: "src/features/clients/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/clients/actions.ts::getClientActivity": {
    actionName: "getClientActivity",
    modulePath: "src/features/clients/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/clients/actions.ts::createClient": {
    actionName: "createClient",
    modulePath: "src/features/clients/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/clients/actions.ts::updateClient": {
    actionName: "updateClient",
    modulePath: "src/features/clients/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/clients/actions.ts::archiveClient": {
    actionName: "archiveClient",
    modulePath: "src/features/clients/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/clients/actions.ts::createContact": {
    actionName: "createContact",
    modulePath: "src/features/clients/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/clients/actions.ts::updateContact": {
    actionName: "updateContact",
    modulePath: "src/features/clients/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/clients/actions.ts::archiveContact": {
    actionName: "archiveContact",
    modulePath: "src/features/clients/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/clients/actions.ts::getClientsCount": {
    actionName: "getClientsCount",
    modulePath: "src/features/clients/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/deliverables/actions.ts::createDeliverable": {
    actionName: "createDeliverable",
    modulePath: "src/features/deliverables/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/deliverables/actions.ts::startReviewSession": {
    actionName: "startReviewSession",
    modulePath: "src/features/deliverables/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/deliverables/actions.ts::approveRevision": {
    actionName: "approveRevision",
    modulePath: "src/features/deliverables/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/deliverables/actions.ts::requestRevision": {
    actionName: "requestRevision",
    modulePath: "src/features/deliverables/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/deliverables/actions.ts::generateShareLink": {
    actionName: "generateShareLink",
    modulePath: "src/features/deliverables/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/deliverables/actions.ts::getReviewSessions": {
    actionName: "getReviewSessions",
    modulePath: "src/features/deliverables/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/deliverables/actions.ts::getDeliverableApprovals": {
    actionName: "getDeliverableApprovals",
    modulePath: "src/features/deliverables/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/deliverables/actions.ts::getDeliverableShareLinks": {
    actionName: "getDeliverableShareLinks",
    modulePath: "src/features/deliverables/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/deliverables/actions.ts::getDeliverableActivity": {
    actionName: "getDeliverableActivity",
    modulePath: "src/features/deliverables/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/deliverables/actions.ts::getDeliverables": {
    actionName: "getDeliverables",
    modulePath: "src/features/deliverables/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/deliverables/actions.ts::getDeliverableById": {
    actionName: "getDeliverableById",
    modulePath: "src/features/deliverables/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/deliverables/actions.ts::searchDeliverables": {
    actionName: "searchDeliverables",
    modulePath: "src/features/deliverables/actions.ts",
    policy: RATE_LIMITS.searchExpensive,
    keyResolver: "userAndOrg",
    resourceBounds: "query [2, 64], max results 50",
    authorization: "requireCurrentUser",
  },
  "src/features/files/actions.ts::createFolder": {
    actionName: "createFolder",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::updateFolder": {
    actionName: "updateFolder",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::deleteFolder": {
    actionName: "deleteFolder",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::updateFile": {
    actionName: "updateFile",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::deleteFile": {
    actionName: "deleteFile",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::getProjectFolders": {
    actionName: "getProjectFolders",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::getFileVersions": {
    actionName: "getFileVersions",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::getFileShares": {
    actionName: "getFileShares",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::getFileActivity": {
    actionName: "getFileActivity",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::initializeFileUpload": {
    actionName: "initializeFileUpload",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::finalizeFileUpload": {
    actionName: "finalizeFileUpload",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::linkFileToEntity": {
    actionName: "linkFileToEntity",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::generateShareLink": {
    actionName: "generateShareLink",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::promoteFileVersion": {
    actionName: "promoteFileVersion",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::getFiles": {
    actionName: "getFiles",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::getFolder": {
    actionName: "getFolder",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/files/actions.ts::searchFiles": {
    actionName: "searchFiles",
    modulePath: "src/features/files/actions.ts",
    policy: RATE_LIMITS.searchExpensive,
    keyResolver: "userAndOrg",
    resourceBounds: "query [2, 64], max results 50",
    authorization: "requireCurrentUser",
  },
  "src/features/meetings/actions.ts::createMeeting": {
    actionName: "createMeeting",
    modulePath: "src/features/meetings/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/actions.ts::updateMeeting": {
    actionName: "updateMeeting",
    modulePath: "src/features/meetings/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/actions.ts::cancelMeeting": {
    actionName: "cancelMeeting",
    modulePath: "src/features/meetings/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/actions.ts::completeMeeting": {
    actionName: "completeMeeting",
    modulePath: "src/features/meetings/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/actions.ts::addMeetingAttendee": {
    actionName: "addMeetingAttendee",
    modulePath: "src/features/meetings/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/actions.ts::updateMeetingAttendee": {
    actionName: "updateMeetingAttendee",
    modulePath: "src/features/meetings/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/actions.ts::removeMeetingAttendee": {
    actionName: "removeMeetingAttendee",
    modulePath: "src/features/meetings/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/actions.ts::addAgendaItem": {
    actionName: "addAgendaItem",
    modulePath: "src/features/meetings/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/actions.ts::updateAgendaItem": {
    actionName: "updateAgendaItem",
    modulePath: "src/features/meetings/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/actions.ts::removeAgendaItem": {
    actionName: "removeAgendaItem",
    modulePath: "src/features/meetings/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/actions.ts::createDecision": {
    actionName: "createDecision",
    modulePath: "src/features/meetings/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/actions.ts::createActionItem": {
    actionName: "createActionItem",
    modulePath: "src/features/meetings/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/actions.ts::promoteActionItemToTask": {
    actionName: "promoteActionItemToTask",
    modulePath: "src/features/meetings/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/queries.ts::getMeetingsForProject": {
    actionName: "getMeetingsForProject",
    modulePath: "src/features/meetings/queries.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/queries.ts::getMeetingById": {
    actionName: "getMeetingById",
    modulePath: "src/features/meetings/queries.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/queries.ts::getMeetingDecisions": {
    actionName: "getMeetingDecisions",
    modulePath: "src/features/meetings/queries.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/queries.ts::getMeetingActionItems": {
    actionName: "getMeetingActionItems",
    modulePath: "src/features/meetings/queries.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/queries.ts::getMeetings": {
    actionName: "getMeetings",
    modulePath: "src/features/meetings/queries.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/queries.ts::getMeetingAttendees": {
    actionName: "getMeetingAttendees",
    modulePath: "src/features/meetings/queries.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/queries.ts::getMeetingAgenda": {
    actionName: "getMeetingAgenda",
    modulePath: "src/features/meetings/queries.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/queries.ts::getMeetingOutcomes": {
    actionName: "getMeetingOutcomes",
    modulePath: "src/features/meetings/queries.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/meetings/queries.ts::getMeetingActivity": {
    actionName: "getMeetingActivity",
    modulePath: "src/features/meetings/queries.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/notifications/actions.ts::getNotificationsAction": {
    actionName: "getNotificationsAction",
    modulePath: "src/features/notifications/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/notifications/actions.ts::getNotificationFeedAction": {
    actionName: "getNotificationFeedAction",
    modulePath: "src/features/notifications/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/notifications/actions.ts::markNotificationUnreadAction": {
    actionName: "markNotificationUnreadAction",
    modulePath: "src/features/notifications/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/notifications/actions.ts::markAllNotificationsReadAction": {
    actionName: "markAllNotificationsReadAction",
    modulePath: "src/features/notifications/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/notifications/actions.ts::markNotificationReadAction": {
    actionName: "markNotificationReadAction",
    modulePath: "src/features/notifications/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/notifications/actions.ts::updateNotificationPreferencesAction": {
    actionName: "updateNotificationPreferencesAction",
    modulePath: "src/features/notifications/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/notifications/queries.ts::getNotificationsQuery": {
    actionName: "getNotificationsQuery",
    modulePath: "src/features/notifications/queries.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/notifications/queries.ts::getNotificationPreferencesQuery": {
    actionName: "getNotificationPreferencesQuery",
    modulePath: "src/features/notifications/queries.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/organizations/actions.ts::getOrganization": {
    actionName: "getOrganization",
    modulePath: "src/features/organizations/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/organizations/actions.ts::updateOrganization": {
    actionName: "updateOrganization",
    modulePath: "src/features/organizations/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/organizations/actions.ts::getRoles": {
    actionName: "getRoles",
    modulePath: "src/features/organizations/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/organizations/actions.ts::getOrganizationMembers": {
    actionName: "getOrganizationMembers",
    modulePath: "src/features/organizations/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/organizations/actions.ts::getPendingInvitations": {
    actionName: "getPendingInvitations",
    modulePath: "src/features/organizations/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/organizations/actions.ts::updateUserRole": {
    actionName: "updateUserRole",
    modulePath: "src/features/organizations/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/organizations/actions.ts::deactivateUser": {
    actionName: "deactivateUser",
    modulePath: "src/features/organizations/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/organizations/actions.ts::reactivateUser": {
    actionName: "reactivateUser",
    modulePath: "src/features/organizations/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/organizations/departments/actions.ts::listDepartmentsAction": {
    actionName: "listDepartmentsAction",
    modulePath: "src/features/organizations/departments/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/organizations/departments/actions.ts::getDepartmentAction": {
    actionName: "getDepartmentAction",
    modulePath: "src/features/organizations/departments/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/organizations/onboarding-actions.ts::createOrganizationAction": {
    actionName: "createOrganizationAction",
    modulePath: "src/features/organizations/onboarding-actions.ts",
    policy: RATE_LIMITS.orgCreation,
    keyResolver: "userOrIp",
    resourceBounds: "org name [2, 100], slug [2, 50], codePrefix [2, 8]",
    authorization: "requireCurrentUser",
  },
  "src/features/organizations/onboarding-actions.ts::acceptInvitationAction": {
    actionName: "acceptInvitationAction",
    modulePath: "src/features/organizations/onboarding-actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/organizations/onboarding-actions.ts::previewInvitationAction": {
    actionName: "previewInvitationAction",
    modulePath: "src/features/organizations/onboarding-actions.ts",
    policy: RATE_LIMITS.invitationPreview,
    keyResolver: "invitationTokenPrefixBucket",
    resourceBounds: "rawToken max 256",
    authorization: "public / token verify",
  },
  "src/features/organizations/onboarding-actions.ts::switchOrganizationAction": {
    actionName: "switchOrganizationAction",
    modulePath: "src/features/organizations/onboarding-actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/organizations/onboarding-actions.ts::inviteMemberAction": {
    actionName: "inviteMemberAction",
    modulePath: "src/features/organizations/onboarding-actions.ts",
    policy: RATE_LIMITS.invitationIssuance,
    keyResolver: "userAndOrg",
    resourceBounds: "email max 255, roleId uuid, departmentId uuid",
    authorization: "requireCurrentUser + requirePermission(organizations, manage)",
  },
  "src/features/organizations/onboarding-actions.ts::revokeInvitationAction": {
    actionName: "revokeInvitationAction",
    modulePath: "src/features/organizations/onboarding-actions.ts",
    policy: RATE_LIMITS.invitationIssuance,
    keyResolver: "userAndOrg",
    resourceBounds: "email max 255, roleId uuid, departmentId uuid",
    authorization: "requireCurrentUser + requirePermission(organizations, manage)",
  },
  "src/features/projects/actions.ts::createProject": {
    actionName: "createProject",
    modulePath: "src/features/projects/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/projects/actions.ts::updateProject": {
    actionName: "updateProject",
    modulePath: "src/features/projects/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/projects/actions.ts::getProjects": {
    actionName: "getProjects",
    modulePath: "src/features/projects/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/projects/actions.ts::getProjectById": {
    actionName: "getProjectById",
    modulePath: "src/features/projects/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/projects/actions.ts::archiveProject": {
    actionName: "archiveProject",
    modulePath: "src/features/projects/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/projects/actions.ts::getProjectDashboardSummary": {
    actionName: "getProjectDashboardSummary",
    modulePath: "src/features/projects/actions.ts",
    policy: RATE_LIMITS.reportExpensive,
    keyResolver: "userAndOrg",
    resourceBounds: "date range <= 31 days, max rows 1000",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/projects/actions.ts::addProjectMember": {
    actionName: "addProjectMember",
    modulePath: "src/features/projects/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/projects/actions.ts::updateProjectMemberRole": {
    actionName: "updateProjectMemberRole",
    modulePath: "src/features/projects/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/projects/actions.ts::removeProjectMember": {
    actionName: "removeProjectMember",
    modulePath: "src/features/projects/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/projects/actions.ts::getActiveProjectsCount": {
    actionName: "getActiveProjectsCount",
    modulePath: "src/features/projects/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/revisions/actions.ts::createRevisionRequest": {
    actionName: "createRevisionRequest",
    modulePath: "src/features/revisions/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/revisions/actions.ts::createRevision": {
    actionName: "createRevision",
    modulePath: "src/features/revisions/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/revisions/actions.ts::updateRevisionStatus": {
    actionName: "updateRevisionStatus",
    modulePath: "src/features/revisions/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/revisions/actions.ts::assignRevision": {
    actionName: "assignRevision",
    modulePath: "src/features/revisions/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/revisions/actions.ts::mergeRevision": {
    actionName: "mergeRevision",
    modulePath: "src/features/revisions/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/revisions/actions.ts::rollbackRevision": {
    actionName: "rollbackRevision",
    modulePath: "src/features/revisions/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/search/actions.ts::globalSearch": {
    actionName: "globalSearch",
    modulePath: "src/features/search/actions.ts",
    policy: RATE_LIMITS.searchExpensive,
    keyResolver: "userAndOrg",
    resourceBounds: "query [2, 64], max results 50",
    authorization: "requireCurrentUser",
  },
  "src/features/shares/actions/index.ts::createShareSessionAction": {
    actionName: "createShareSessionAction",
    modulePath: "src/features/shares/actions/index.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "ipOnly",
    resourceBounds: "domain Zod schema bounds",
    authorization: "validateToken / portalSession",
  },
  "src/features/shares/actions/index.ts::resolveExternalIdentityAction": {
    actionName: "resolveExternalIdentityAction",
    modulePath: "src/features/shares/actions/index.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "ipOnly",
    resourceBounds: "domain Zod schema bounds",
    authorization: "validateToken / portalSession",
  },
  "src/features/shares/actions/index.ts::submitExternalCommentAction": {
    actionName: "submitExternalCommentAction",
    modulePath: "src/features/shares/actions/index.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "ipOnly",
    resourceBounds: "domain Zod schema bounds",
    authorization: "validateToken / portalSession",
  },
  "src/features/shares/actions/index.ts::submitExternalAnnotationAction": {
    actionName: "submitExternalAnnotationAction",
    modulePath: "src/features/shares/actions/index.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "ipOnly",
    resourceBounds: "domain Zod schema bounds",
    authorization: "validateToken / portalSession",
  },
  "src/features/shares/actions/index.ts::submitExternalApprovalAction": {
    actionName: "submitExternalApprovalAction",
    modulePath: "src/features/shares/actions/index.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "ipOnly",
    resourceBounds: "domain Zod schema bounds",
    authorization: "validateToken / portalSession",
  },
  "src/features/shares/actions/index.ts::requestShareMeetingAction": {
    actionName: "requestShareMeetingAction",
    modulePath: "src/features/shares/actions/index.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "ipOnly",
    resourceBounds: "domain Zod schema bounds",
    authorization: "validateToken / portalSession",
  },
  "src/features/tasks/actions.ts::createTask": {
    actionName: "createTask",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/tasks/actions.ts::updateTask": {
    actionName: "updateTask",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/tasks/actions.ts::getTasks": {
    actionName: "getTasks",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/tasks/actions.ts::startTaskTimer": {
    actionName: "startTaskTimer",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/tasks/actions.ts::stopTaskTimer": {
    actionName: "stopTaskTimer",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/tasks/actions.ts::addTaskDependency": {
    actionName: "addTaskDependency",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/tasks/actions.ts::getMyOpenTasksCount": {
    actionName: "getMyOpenTasksCount",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/tasks/actions.ts::deleteTask": {
    actionName: "deleteTask",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/tasks/actions.ts::assignTask": {
    actionName: "assignTask",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/tasks/actions.ts::unassignTask": {
    actionName: "unassignTask",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/tasks/actions.ts::getTaskAssignees": {
    actionName: "getTaskAssignees",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/tasks/actions.ts::addTaskComment": {
    actionName: "addTaskComment",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/tasks/actions.ts::getTaskComments": {
    actionName: "getTaskComments",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/tasks/actions.ts::getTaskActivity": {
    actionName: "getTaskActivity",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/tasks/actions.ts::searchTasks": {
    actionName: "searchTasks",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.searchExpensive,
    keyResolver: "userAndOrg",
    resourceBounds: "query [2, 64], max results 50",
    authorization: "requireCurrentUser",
  },
  "src/features/tasks/actions.ts::getActiveTaskTimer": {
    actionName: "getActiveTaskTimer",
    modulePath: "src/features/tasks/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/timelines/actions.ts::createTimeline": {
    actionName: "createTimeline",
    modulePath: "src/features/timelines/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/timelines/actions.ts::getProjectTimeline": {
    actionName: "getProjectTimeline",
    modulePath: "src/features/timelines/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/timelines/actions.ts::getTimelines": {
    actionName: "getTimelines",
    modulePath: "src/features/timelines/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/timelines/actions.ts::getTimelineMilestones": {
    actionName: "getTimelineMilestones",
    modulePath: "src/features/timelines/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/timelines/actions.ts::getTimelineDependencies": {
    actionName: "getTimelineDependencies",
    modulePath: "src/features/timelines/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/timelines/actions.ts::createMilestone": {
    actionName: "createMilestone",
    modulePath: "src/features/timelines/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/timelines/actions.ts::addTimelineDependency": {
    actionName: "addTimelineDependency",
    modulePath: "src/features/timelines/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/users/actions.ts::getMyProfile": {
    actionName: "getMyProfile",
    modulePath: "src/features/users/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/users/actions.ts::updateMyProfile": {
    actionName: "updateMyProfile",
    modulePath: "src/features/users/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/users/admin/actions.ts::createEmployeeAction": {
    actionName: "createEmployeeAction",
    modulePath: "src/features/users/admin/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/users/admin/actions.ts::updateEmployeeAction": {
    actionName: "updateEmployeeAction",
    modulePath: "src/features/users/admin/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/users/admin/actions.ts::setEmployeeStatusAction": {
    actionName: "setEmployeeStatusAction",
    modulePath: "src/features/users/admin/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/users/admin/actions.ts::archiveEmployeeAction": {
    actionName: "archiveEmployeeAction",
    modulePath: "src/features/users/admin/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/users/admin/actions.ts::restoreEmployeeAction": {
    actionName: "restoreEmployeeAction",
    modulePath: "src/features/users/admin/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/users/admin/actions.ts::assignDepartmentAction": {
    actionName: "assignDepartmentAction",
    modulePath: "src/features/users/admin/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/users/admin/actions.ts::assignManagerAction": {
    actionName: "assignManagerAction",
    modulePath: "src/features/users/admin/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/actions.ts::clockInAction": {
    actionName: "clockInAction",
    modulePath: "src/features/workforce/attendance/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/actions.ts::clockOutAction": {
    actionName: "clockOutAction",
    modulePath: "src/features/workforce/attendance/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/actions.ts::startBreakAction": {
    actionName: "startBreakAction",
    modulePath: "src/features/workforce/attendance/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/actions.ts::endBreakAction": {
    actionName: "endBreakAction",
    modulePath: "src/features/workforce/attendance/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/actions.ts::getTodayAttendanceAction": {
    actionName: "getTodayAttendanceAction",
    modulePath: "src/features/workforce/attendance/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/actions.ts::getAttendanceTimelineAction": {
    actionName: "getAttendanceTimelineAction",
    modulePath: "src/features/workforce/attendance/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/actions.ts::listAttendanceAction": {
    actionName: "listAttendanceAction",
    modulePath: "src/features/workforce/attendance/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/actions.ts::getAttendanceAction": {
    actionName: "getAttendanceAction",
    modulePath: "src/features/workforce/attendance/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/actions.ts::getAttendanceHistoryAction": {
    actionName: "getAttendanceHistoryAction",
    modulePath: "src/features/workforce/attendance/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/actions.ts::getTeamAttendanceAction": {
    actionName: "getTeamAttendanceAction",
    modulePath: "src/features/workforce/attendance/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/form-actions.ts::submitClockIn": {
    actionName: "submitClockIn",
    modulePath: "src/features/workforce/attendance/form-actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/form-actions.ts::submitClockOut": {
    actionName: "submitClockOut",
    modulePath: "src/features/workforce/attendance/form-actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/form-actions.ts::submitStartBreak": {
    actionName: "submitStartBreak",
    modulePath: "src/features/workforce/attendance/form-actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/form-actions.ts::submitEndBreak": {
    actionName: "submitEndBreak",
    modulePath: "src/features/workforce/attendance/form-actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/read-model-actions.ts::getWorkforceDashboardMetricsAction": {
    actionName: "getWorkforceDashboardMetricsAction",
    modulePath: "src/features/workforce/attendance/read-model-actions.ts",
    policy: RATE_LIMITS.reportExpensive,
    keyResolver: "userAndOrg",
    resourceBounds: "date range <= 31 days, max rows 1000",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/attendance/read-model-actions.ts::getWorkforceReportAction": {
    actionName: "getWorkforceReportAction",
    modulePath: "src/features/workforce/attendance/read-model-actions.ts",
    policy: RATE_LIMITS.reportExpensive,
    keyResolver: "userAndOrg",
    resourceBounds: "date range <= 31 days, max rows 1000",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/corrections/actions.ts::submitCorrectionAction": {
    actionName: "submitCorrectionAction",
    modulePath: "src/features/workforce/corrections/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/corrections/actions.ts::cancelCorrectionAction": {
    actionName: "cancelCorrectionAction",
    modulePath: "src/features/workforce/corrections/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/corrections/actions.ts::markCorrectionUnderReviewAction": {
    actionName: "markCorrectionUnderReviewAction",
    modulePath: "src/features/workforce/corrections/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/corrections/actions.ts::reviewCorrectionAction": {
    actionName: "reviewCorrectionAction",
    modulePath: "src/features/workforce/corrections/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/corrections/actions.ts::listMyCorrectionsAction": {
    actionName: "listMyCorrectionsAction",
    modulePath: "src/features/workforce/corrections/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/corrections/actions.ts::getCorrectionAction": {
    actionName: "getCorrectionAction",
    modulePath: "src/features/workforce/corrections/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/corrections/actions.ts::listCorrectionReviewQueueAction": {
    actionName: "listCorrectionReviewQueueAction",
    modulePath: "src/features/workforce/corrections/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/corrections/actions.ts::getCorrectionReviewContextAction": {
    actionName: "getCorrectionReviewContextAction",
    modulePath: "src/features/workforce/corrections/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/corrections/form-actions.ts::submitCorrection": {
    actionName: "submitCorrection",
    modulePath: "src/features/workforce/corrections/form-actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/corrections/form-actions.ts::cancelCorrection": {
    actionName: "cancelCorrection",
    modulePath: "src/features/workforce/corrections/form-actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/corrections/form-actions.ts::markUnderReview": {
    actionName: "markUnderReview",
    modulePath: "src/features/workforce/corrections/form-actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/corrections/form-actions.ts::decideCorrection": {
    actionName: "decideCorrection",
    modulePath: "src/features/workforce/corrections/form-actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/employees/actions.ts::listEmployeesAction": {
    actionName: "listEmployeesAction",
    modulePath: "src/features/workforce/employees/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/employees/actions.ts::getEmployeeAction": {
    actionName: "getEmployeeAction",
    modulePath: "src/features/workforce/employees/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/employees/actions.ts::listDirectReportsAction": {
    actionName: "listDirectReportsAction",
    modulePath: "src/features/workforce/employees/actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/features/workforce/shared/policy-actions.ts::getWorkforcePolicyAction": {
    actionName: "getWorkforcePolicyAction",
    modulePath: "src/features/workforce/shared/policy-actions.ts",
    policy: RATE_LIMITS.resourceRead,
    keyResolver: "userAndOrg",
    resourceBounds: "pagination page >= 1, pageSize <= 100",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/lib/agents/actions.ts::createAgentAction": {
    actionName: "createAgentAction",
    modulePath: "src/lib/agents/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/lib/agents/actions.ts::startAgentRunAction": {
    actionName: "startAgentRunAction",
    modulePath: "src/lib/agents/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/lib/agents/actions.ts::pauseAgentRunAction": {
    actionName: "pauseAgentRunAction",
    modulePath: "src/lib/agents/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/lib/agents/actions.ts::resumeAgentRunAction": {
    actionName: "resumeAgentRunAction",
    modulePath: "src/lib/agents/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/lib/agents/actions.ts::cancelAgentRunAction": {
    actionName: "cancelAgentRunAction",
    modulePath: "src/lib/agents/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/lib/automation/actions.ts::createWorkflow": {
    actionName: "createWorkflow",
    modulePath: "src/lib/automation/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/lib/automation/actions.ts::publishWorkflowVersion": {
    actionName: "publishWorkflowVersion",
    modulePath: "src/lib/automation/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/lib/automation/actions.ts::triggerManualWorkflow": {
    actionName: "triggerManualWorkflow",
    modulePath: "src/lib/automation/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/lib/automation/actions.ts::cancelExecutionRun": {
    actionName: "cancelExecutionRun",
    modulePath: "src/lib/automation/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
  "src/lib/automation/actions.ts::replayDlqItem": {
    actionName: "replayDlqItem",
    modulePath: "src/lib/automation/actions.ts",
    policy: RATE_LIMITS.resourceMutation,
    keyResolver: "userAndOrg",
    resourceBounds: "domain Zod schema bounds",
    authorization: "requireCurrentUser + requirePermission",
  },
};

export interface VerificationResult {
  readonly valid: boolean;
  readonly totalDiscovered: number;
  readonly totalRegistered: number;
  readonly unmappedActions: readonly string[];
  readonly conflictingMappings: readonly string[];
}

/**
 * Machine-verifies that every public action exported from public action modules
 * is accounted for in ACTION_POLICY_REGISTRY with zero unmapped actions and zero conflicts.
 */
export function verifyActionRegistry(
  readFileFn?: (path: string) => string,
): VerificationResult {
  const read = readFileFn ?? ((p: string) => readFileSync(p, "utf8"));

  const discoveredActions: string[] = [];
  const conflicts: string[] = [];
  const seen = new Set<string>();

  for (const mod of PUBLIC_ACTION_MODULES) {
    const content = read(mod);
    const matches = [...content.matchAll(/export\s+async\s+function\s+(\w+)/g)].map(
      (m) => m[1],
    );

    for (const action of matches) {
      const key = `${mod}::${action}`;
      if (seen.has(key)) {
        conflicts.push(key);
      }
      seen.add(key);
      discoveredActions.push(key);
    }
  }

  const registeredKeys = Object.keys(ACTION_POLICY_REGISTRY);
  const unmappedActions = discoveredActions.filter(
    (key) => !(key in ACTION_POLICY_REGISTRY),
  );

  return {
    valid: unmappedActions.length === 0 && conflicts.length === 0,
    totalDiscovered: discoveredActions.length,
    totalRegistered: registeredKeys.length,
    unmappedActions,
    conflictingMappings: conflicts,
  };
}

export function getActionPolicy(
  modulePath: string,
  actionName: string,
): ActionPolicyMapping | undefined {
  return ACTION_POLICY_REGISTRY[`${modulePath}::${actionName}`];
}
