-- ============================================================================
-- AI NEX OS — organization_sequences composite primary key (Sprint 2.3)
--
-- `organization_sequences` was created in 0004 with a unique index on
-- (organization_id, entity_type) but no declared primary key, which is what the
-- live schema assertion "gives every table a primary key" was catching.
--
-- The constraint was first added by editing 0004 in place, after 0004 had
-- already been applied. That desynchronised drizzle's recorded content hash
-- from the file, so the repository claimed a history the migrator had never
-- run. 0004 has been reverted to what was actually applied, and the change is
-- expressed here instead — generated by `drizzle-kit generate`, so the snapshot
-- chain carries it forward properly.
--
-- The guard exists because the constraint is ALREADY live on this database: it
-- was pushed directly while the edited 0004 was in place. A bare ADD CONSTRAINT
-- would abort with 42P16 ("multiple primary keys for table are not allowed")
-- and leave the migration permanently unapplyable here, while still being
-- required on a database replayed from empty. The test is on contype = 'p'
-- rather than the constraint name: a table may only ever have one primary key,
-- so any existing one — under any name — means there is nothing to do.
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE n.nspname = 'public'
      AND t.relname = 'organization_sequences'
      AND c.contype = 'p'
  ) THEN
    ALTER TABLE "organization_sequences"
      ADD CONSTRAINT "organization_sequences_organization_id_entity_type_pk"
      PRIMARY KEY ("organization_id", "entity_type");
  END IF;
END
$$;
